name: 2. Build and Publish

on:
  workflow_run:
    workflows: ["1. Bump Version"]
    types:
      - completed
    branches:
      - main
  push:
    tags:
      - "v*.*.*-*"

env:
  _VERSION: {{cookiecutter.version}}

jobs:
  build_publish:
    name: Build and Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}
          password: {% raw %}${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}
      - name: Get version
        run: echo "_VERSION=$(./scripts/get-version.sh)" >> ${GITHUB_ENV}
      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            "HASH_PASSWORD={% raw %}${{ secrets.DOCKER_UID_HASH_PASSWORD }}{% endraw %}"
          load: true
          cache-from: type=registry,ref={% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:cache-latest
          tags: {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:test
      - name: Test docker image
        run: |
          docker run --rm -dt -p 8000:8000 {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:test
          sleep 3
          curl -s http://localhost:8000/api/v1/ping | grep "Pong"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            "HASH_PASSWORD={% raw %}${{ secrets.DOCKER_UID_HASH_PASSWORD }}{% endraw %}"
          # platforms: linux/amd64
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref={% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:cache-latest
          cache-to: type=registry,ref={% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:cache-latest,mode=max
          tags: |
            {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:latest
            {% raw %}${{ secrets.DOCKERHUB_USERNAME }}{% endraw %}/{{cookiecutter.docker_repo_name}}:{% raw %}${{ env._VERSION }}{% endraw %}
          push: true
      - name: Trigger release
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        run: gh workflow run 3.create-release.yml
