env: "LOCAL"
debug: false

api:
  name: "{{cookiecutter.project_name}}"
  slug: "{{cookiecutter.project_slug}}"
  bind_host: "0.0.0.0"
  port: 8000
  version: "1"
  prefix: "/api/v{api_version}"
  gzip_min_size: 1024 # Bytes (1KB)
  behind_proxy: true
  behind_cf_proxy: true
  dev:
    reload: false
    reload_includes: [".env", "*.json", "*.yml", "*.yaml", "*.md"]
    reload_excludes:
      [".*", "~*", ".py[cod]", ".sw.*", "__pycache__", "*.log", "logs"]
