api:
  docs:
    enabled: true
    openapi_url: "{api_prefix}/openapi.json"
    docs_url: "{api_prefix}/docs"
    redoc_url: "{api_prefix}/redoc"
    swagger_ui_oauth2_redirect_url: "{api_prefix}/docs/oauth2-redirect"
    summary: "This is a REST API service."
    description: ""
    terms_of_service: "https://{{cookiecutter.domain}}/terms"
    contact:
      name: "Support Team"
      email: "support@{{cookiecutter.domain}}"
      url: "https://{{cookiecutter.domain}}/contact"
    openapi_tags:
      - name: "Utils"
        description: "Useful utility endpoints."
      - name: "Default"
        description: "Redirection of default endpoints."
    swagger_ui_parameters:
      syntaxHighlight.theme: "nord"
