name: 1. Bump Version

on:
  workflow_dispatch:
    inputs:
      bump_type:
        type: choice
        description: "Choose bump version type:"
        required: true
        options: ["patch", "minor", "major"]

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Bump version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          export VERSION_FILENAME="app/__version__.py"
          ./scripts/bump-version.sh ${{ inputs.bump_type }}
          gh workflow run 2.build-publish.yml -r v$(< "${VERSION_FILENAME}" grep "__version__ = " | awk -F' = ' '{print $2}' | tr -d '"')
